<?php
$_order = Mage::registry('current_order');

if (!$_order) {
    return;
}

$_comment = $_order->getFirecheckoutCustomerComment();
if (!$_comment) {
    return;
}

?>

<div class="box-left" id="firecheckout_comment">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-firecheckout-comment"><?php echo $this->__('Comment') ?></h4>
        </div>
        <fieldset>
            <?php echo $this->escapeHtml($_comment) ?>
        </fieldset>
    </div>
</div>

<script type="text/javascript">
document.observe('dom:loaded', function() {
    var div = $('sales_order_view_tabs_order_info_content').down('div');
    div.insert({
        bottom: $('firecheckout_comment')
    });
    div.insert({
        bottom: '<div class="clear"></div>'
    });
});
</script>
