<?php if ($this->getQuote()->isVirtual()) : return; endif; ?>
<div id="shipping-method" class="firecheckout-section">
    <div class="block-title"><span><?php echo $this->__('Shipping Method') ?></span><span id="shipping-method-reset"><?php echo $this->__('Reset') ?></span></div>
    <div class="block-content">
        <div id="checkout-shipping-method-load">
            <?php echo $this->getChildHtml('available') ?>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            var shippingMethod = new ShippingMethod('shipping-method');
        //]]>
        </script>
        <?php echo $this->getChildHtml('delivery_date') ?>
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php echo $this->getChildHtml('additional') ?>
        </div>

        <?php echo $this->getChildHtml('wsa-accessorials') ?>
    </div>
</div>