<?php
    $comment = Mage::getStoreConfig('firecheckout/general/comment');
    $salesrep = Mage::getStoreConfig('salesrep/setup/enabled') && Mage::getStoreConfig('salesrep/step_setup/step_enabled');
    $checkoutFields = $this->getChildHtml('checkoutfields');
?>

<?php if ($comment || $salesrep || $checkoutFields) : ?>
    <div id="checkout-additional" class="firecheckout-section">
        <div class="block-title"><span><?php echo $this->__('Additional Information') ?></span></div>
        <?php if (Mage::getStoreConfig('firecheckout/general/comment')) : ?>
        <ul class="form-list form-comment">
            <li class="wide">
                <label for="order-comment"><?php echo $this->helper('sales')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="order-comment" id="order-comment" rows="5" cols="25"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
                </div>
            </li>
        </ul>
        <?php endif; ?>

        <?php if (Mage::getStoreConfig('salesrep/setup/enabled') && Mage::getStoreConfig('salesrep/step_setup/step_enabled')) : ?>
        <?php $admins = Mage::helper('salesrep')->getUsersList(); ?>
        <ul class="form-list">
            <li>
                <label for="getvoice" class="required"><em>*</em><?php echo Mage::getStoreConfig('salesrep/step_setup/step_label')?></label>
                <div class="input-box">
                    <select id="getvoice" name="getvoice" class="validate-select">
                        <option value=""></option>
                        <option value="<?php echo $this->__('No Sales Representative') ?>"><?php echo $this->__('No Sales Representative') ?></option>
                        <?php foreach($admins as $admin): ?>
                        <option value="<?php echo $admin['label'] ?>"><?php echo $admin['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div style="display: none;" id="advice-validate-select-getvoice" class="validation-advice">
                    <?php echo Mage::getStoreConfig('salesrep/step_setup/step_error_msg')?>
                </div>
            </li>
        </ul>
        <?php endif; ?>

        <?php echo $checkoutFields ?>
    </div>
<?php endif; ?>

<div id="checkout-review" class="firecheckout-section">
    <div class="block-title"><span><?php echo $this->__('Checkout Review') ?></span></div>
    <?php $agreements = $this->getChildHtml('agreements') ?>
    <?php if (!empty($agreements)) : ?>
        <div id="agreements-wrapper">
            <?php echo $agreements; ?>
        </div>
    <?php endif; ?>
    <div id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[
            review = new Review(); // dummy class for various payment methods
        //]]>
    </script>
    <div id="checkout-review-submit">
        <div class="buttons-set" id="review-buttons-container">
            <button type="button" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="checkout.save(); return false;"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
            <span class="please-wait" id="review-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
        </div>
    </div>
</div>