<!--gift card section-->
<?php if(!Mage::getStoreConfig('giftcards/default/show_as_payment_method')): return; endif; ?>

<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<div id="giftcard-section">
    <div class="discount" style="padding: 0 10px; margin-bottom: 5px;">
        <div class="sp-methods">
            <?php //echo $this->getUrl('giftcards/cart/giftcardActive'); ?>
            <div class="input-box">
                <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox" onclick="agreeMethod.save();" <?php echo $oGiftCardSession->getActive() ? 'checked="checked"' : '' ?>>
                <label for="giftcard_use"><?php echo $this->__('Gift Card'); ?></label>
            </div>
        </div>
        <?php if($oGiftCardSession->getActive()): ?>
        <div class="discount-form giftcard-payment-method">
        <?php //echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>
            <label for="giftcard_code"><?php echo $this->__('Redeem and use your Gift Card now:'); ?></label>
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Apply') ?>" onclick="activateGiftCard.save()" class="button"
                        title="Apply" type="button" style="float: left;"><span><span><?php echo $this->__('Apply') ?></span></span>
                </button>
            </div>

            <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
            <?php if ($oGiftCardSession->getActive()) {
                foreach($oGiftCardSession->getFrontOptions() as $k => $v) {
                    if($temp) {
                        echo '<br/><br/>';
                    }
                    echo '<b>'.$currencySymbol.$v['applied'].$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                    echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="#" onclick="deActivateGiftCard.deactivate('.$k.');">'.$this->__('Remove').'</a>)';
                    $temp = 1;
                }
            } ?>
        </div>
        <?php endif;?>
    </div>
</div>
<!-- end gift card section-->
