<script type="text/javascript">
//<![CDATA[
    var activateGiftCard = new OnepageGiftcard('activateGiftCard',"<?php echo $this->getUrl('giftcards/cart/ajaxActivateGiftCard', array('_secure' => true)) ?>");
    var agreeMethod = new OnepageGiftcard('giftcardAgree', "<?php echo $this->getUrl('giftcards/cart/agreeToUse', array('_secure' => true)) ?>");
    var deActivateGiftCard = new OnepageGiftcard( null, "<?php echo $this->getUrl('giftcards/cart/ajaxDeActivateGiftCard', array('_secure' => true)) ?>");

    if (payment) {
        var webtexgiftcardsInit = function() {
            var elements = $('giftcard-section').select('input', 'select', 'textarea');
            for (var i=0; i<elements.length; i++) {
                elements[i].disabled = false;
            }
        }
        payment.addAfterInitFunction('webtexgiftcards', webtexgiftcardsInit.bind(payment));
    }
//]]>
</script>
