<div class="row reasons">
	<div class="col-md-12" style="width: 892px;">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('reason_list_why')->toHtml(); ?>
	</div>
</div>
<div class="row reasons">
	<div class="col-md-12">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('reason_image_why')->toHtml(); ?>
	</div>
</div>
<div class="row reviews">
	<div class="col-md-12" style="width: 892px;">
		<h2>What People Are Saying</h2>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('testimonials_why')->toHtml(); ?>
	</div>
</div>