<?php $helper = $this->helper('iwd_productvideo');
$video = $this->getVideo();
if ($helper->isLocalVideoPlayer($video)): ?>
    <video class="local-video-player video-js vjs-default-skin" controls
           preload="none" width="100%" height="100%" <?php if($this->isAutoplayVideo()): ?>autoplay<?php endif; ?>
           poster="<?php echo $helper->GetMediaImageUrl($video['image']) ?>" data-setup="{}">
        <?php echo $helper->GetVideoSource($video); ?>
    </video>
<?php else: ?>
    <?php if ($video['video_type'] == 'youtube'): ?>
        <iframe id="youtube_video_player_<?php echo $video["video_id"] ?>" class="youtube-video-player"
                src="http://www.youtube.com/embed/<?php echo $video['url'] ?>?enablejsapi=1<?php if($this->isAutoplayVideo()): ?>&autoplay=1<?php endif; ?>"
                width="100%" height="100%" frameborder="0"
                webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    <?php elseif ($video['video_type'] == 'vimeo'): ?>
        <iframe class="vimeo-video-player" src="http://player.vimeo.com/video/<?php echo $video['url']; ?><?php if($this->isAutoplayVideo()): ?>?autoplay=1<?php endif; ?>"
                width="100%" height="100%" frameborder="0"
                webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    <?php endif; ?>
<?php endif; ?>