<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Facebook
 * @author      Ivan Weiler <ivan.weiler@gmail.com>
 * @copyright   Inchoo (http://inchoo.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-login facebook-login">
    <div class="page-title">
        <h2><?php echo $this->__('Connect with Facebook') ?></h2>
    </div>
	<div class="content new-users" style="min-height: 100px;">
		<p><?php echo $this->__( 'Use your Facebook account to quickly login and register with our store. You\'re just one click away and it\'s safe, fast and secure' ) ?></p>
		<div class="buttons-set">
			<button rel="facebook-connect" class="facebook-connect" type="submit">Connect with Facebook</button></span>
		</div>
	</div>
</div>