<?php if (!$methods = $this->getMethods()) : ?>
<p><?php echo $this->helper('checkout')->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else : ?>
<dl class="sp-methods">
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
//]]>
</script>
    <?php $buyerprotect = $this->getChildHtml('buyerprotect');
    if (!empty($buyerprotect)) :
        echo $buyerprotect;
    ?>
        <script type="text/javascript">
        //<![CDATA[
        var trustedCheckbox = $('trusted_shops');
        trustedCheckbox.observe('click', function() {
            checkout.update('<?php echo $this->getUrl('firecheckout/index/buyerprotect', array('_secure'=>true)) ?>');
        });
        $('trusted_shops-product').observe('change', function() {
            if (!trustedCheckbox.checked) {
                return;
            }
            checkout.update('<?php echo $this->getUrl('firecheckout/index/buyerprotect', array('_secure'=>true)) ?>');
        });
        //]]>
        </script>
    <?php endif ?>
<?php endif; ?>
