<?php if (Mage::helper('persistent/session')->isPersistent() && !Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <?php $customer = Mage::helper('persistent/session')->getCustomer(); ?>
    <div id="persistent-cart-window" style="display:none;">
        <div class="page-title">
            <span><?php echo Mage::helper('persistent')->__('Welcome, %s!', Mage::helper('core')->escapeHtml($customer->getName(), null)) ?></span>
        </div>
        <div class="content">
            <p><?php
                echo Mage::helper('firecheckout')->__(
                    'You are browsing our store as %s %s',
                    $customer->getName(),
                    $this->getLayout()->createBlock('persistent/header_additional')->toHtml()
                );
            ?></p>
            <p><?php
                $login    = $this->__('Login');
                $register = $this->__('Register');
                echo Mage::helper('firecheckout')->__(
                    'Please %s or %s a new account to place order.',
                    "<a href='" . $this->getUrl('customer/account/login') . "' class='firecheckout-login'>" . $login . "</a>",
                    "<a href='" . $this->getUrl('persistent/index/saveMethod') . "' class='firecheckout-register'>" . $register . "</a>"
                );
            ?></p>
        </div>
    </div>

<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
    persistentWindow = new FireCheckout.Window({
        triggers: {},
        size: {
            maxWidth: 400
        }
    });
    persistentWindow.update($('persistent-cart-window'))
        .setModal(1)
        .show();
});
//]]>
</script>

<?php endif; ?>

