<?php
//version 103
if(Mage::getSingleton('customer/session')->isLoggedIn()):
    if(Mage::getStoreConfig('connector/settings/storecredit')) {
        $cart_qty = (int) Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
        if($cart_qty==0 || $cart_qty=='')
        {
            Mage::getSingleton('checkout/session')->unsMultiData();
            Mage::getSingleton('core/session')->unsCreditData();
            Mage::getSingleton('checkout/session')->unsCreditData();
            Mage::getSingleton('checkout/session')->unsCreditFinalData();
            Mage::getSingleton('checkout/session')->unsCreditDiscountData();
            Mage::getSingleton('checkout/session')->unsGiftBuyData();
        }

?>
        <?php
        //Mage::getSingleton('checkout/session')->unsCreditData();
        //Mage::getSingleton('checkout/session')->unsCreditFinalData();
        Mage::log("no items cart",null,'giftcardsale.log');
        $creditData = Mage::getSingleton('checkout/session')->getCreditData();
        $arrCreditData = unserialize($creditData);
        $isCredit = 0;
        $creditNo = 0;
        $creditAmt = 0;
        if(count($arrCreditData>0))
        {
            foreach($arrCreditData as $key=>$data)
            {
                if($data['credit_type']==1)
                {
                    $isCredit = 1;
                    $creditNo = $data['credit_no'];
                    $creditAmt = $data['credit_amt'];
                }
            }
        }
        ?>
        <?php
            if($isCredit==1)
            {
                $actionUrl = $this->getUrl('connector/index/mbizUpdateDiscountAmount');
            }
            else
            {
                $actionUrl = $this->getUrl('connector/index/mbizValidateStoreCredit');
            }
        ?>

<div class="cart">
<form id="discount-storecredit-form" action="<?php echo $actionUrl ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('Store Credit Redemption') ?></h2>

        <?php
            if($isCredit==1)
            {
        ?>
               <p style="font-size: 10px"><?php echo $creditNo ?>&nbsp;Current Balance <?php echo $creditAmt; ?>
                   <a class="btn-remove btn-remove2" href="<?php echo $this->getUrl('connector/index/mbizCancelCreditPost/id/'.$creditNo) ?>">&nbsp;&nbsp;Cancel</a><br/>
               </p>
        <?php

            }
        ?>

        <div class="discount-form">
            <?php
                if($isCredit==1)
                {
                    $quote = Mage::getModel('checkout/cart')->getQuote();
                    $cartTotal = $quote->getGrandTotal();
                    if($cartTotal>=$creditAmt)
                    {
                        $amount = $creditAmt;
                    }
                    else
                    {
                        $amount = $cartTotal;
                    }
            ?>
                    <label for="credit_amt"><?php echo $this->__('Amount.') ?></label>
                    <div class="input-box">
                        <input class="input-text" id="credit_amt" name="credit_amt" value="<?php echo $amount ?>" class="required-entry validate-num"/>
                        <input type="hidden" name="credit_no" value="<?php echo $creditNo ?>" />
                        <input type="hidden" name="credit_type" value="1" />
                        <input type="hidden" name="current_bal" value="<?php echo $creditAmt; ?>" />
                    </div>
            <?php
                }
            else{
            ?>
                <label for="credit_no"><?php echo $this->__('Enter your store credit no.') ?></label>
                <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <div class="input-box">
                    <input class="input-text" id="credit_no" name="credit_no" value="" class="required-entry validate-alphanum"/>
                </div>

            <?php
            }
            ?>

            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply Store Credit') ?>" class="button"
                        value="<?php echo $this->__('Apply Store Credit') ?>" onclick="storeCreditForm.submit(false)">
                    <span><span><?php echo $this->__('Apply Store Credit') ?></span></span></button>

                <?php
                $quote = Mage::getModel('checkout/cart')->getQuote();
                $quoteCreditDiscountData = $quote->getCreditDiscountData();
                $quoteCreditDiscountData = unserialize($quoteCreditDiscountData);
                if(count($quoteCreditDiscountData)>0)
                {
                ?>
                <br/><div class="store-credits">
                <?php
                if(is_array($quoteCreditDiscountData))
                {

                    foreach($quoteCreditDiscountData as $data)
                    {
                        if($data['credit_type']==1)
                        {
                            ?>
                            Store Credit (<?php echo $data['credit_no']; ?>) - Amount <?php echo $this->helper('checkout')->formatPrice(-$data['credit_amt']);?>
                            <a class="btn-remove btn-remove2" href="<?php echo $this->getUrl('connector/index/mbizRemoveCreditPost/id/'.$data['credit_no']) ?>">&nbsp;&nbsp;Remove</a><br/>
                            <?php
                        }

                    }

                }
                ?>

                </div>

                <?php
                }
                ?>

            </div>
        </div>
    </div>
</form>
</div>
<?php } ?>
<?php endif;?>
<script type="text/javascript">
    //<![CDATA[
    <?php
     if($isCredit==0)
     {
     ?>
    var storeCreditForm = new VarienForm('discount-storecredit-form');
    storeCreditForm.submit = function (isRemove) {
        if (isRemove) {
            $('credit_no').removeClassName('required-entry');

        } else {
            $('credit_no').addClassName('required-entry');

        }
        return VarienForm.prototype.submit.bind(storeCreditForm)();
    }
    <?php

     }
     else
     {

     ?>
    var storeCreditForm = new VarienForm('discount-storecredit-form');
    storeCreditForm.submit = function (isRemove) {
        if (isRemove) {
            $('credit_amt').removeClassName('required-entry');

        } else {
            $('credit_amt').addClassName('required-entry');

        }
        return VarienForm.prototype.submit.bind(storeCreditForm)();
    }
    <?php
     }
    ?>

    //]]>
</script>
