<?php
//version 100
?>
<?php
$status = $this->getLinkStatus();
$linkData = $this->getLinkData();;
$postedApiFlag = $userNotExists = 0;
Mage::helper('microbiz_connector')->RemoveCaching();
$isLinked = Mage::getStoreConfig('connector/installation/is_linked');
if(!empty($linkData)) {
    $postedApiFlag = $linkData['mbiz_posted_apiusers'];

    if($isLinked && $postedApiFlag) {
        $postedUname = $linkData['mag_api_username'];
        $postedUemail = $linkData['mag_api_email'];
        $magApiUname = Mage::getStoreConfig('connector/installation/mag_api_username');

        $usernameApiModel = Mage::getModel('api/user')->getCollection()
            ->addFieldToFilter('username',$postedUname)
            ->getFirstItem()->getData();
        //print_r($usernameApiModel);
        if(empty($usernameApiModel)) {
            $userNotExists = 1;
        }
        else if($postedUname!=$magApiUname) {
            $userNotExists =1;
        }
        else {
            $userNotExists = 0;
        }
    }
    else if(!$isLinked && $postedApiFlag) {
        $userNotExists =1;
    }


}
/*if(!empty($linkData)) {
$magApiUserName = $linkData['mag_api_username'];
$magApiUserEmail = $linkData['mag_api_email'];
$apiUserData = new Mage_Core_Model_Config();
$apiUserData->saveConfig('connector/installation/mag_api_username',$magApiUserName, 'default', 0);
$apiUserData->saveConfig('connector/installation/mag_api_email',$magApiUserEmail, 'default', 0);

    try {
        $allTypes = Mage::app()->useCache();
        foreach($allTypes as $type => $blah) {
                     //Mage::log($blah);
          Mage::app()->getCacheInstance()->cleanType($type);
        }
        } catch (Exception $e) {
            Mage::log($e->getMessage());
        }
}*/
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head"><?php echo Mage::helper('microbiz_connector')->__('Microbiz POS Plugin Install') ?></h3>

            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="mbiz_install_api_link_form" action="<?php echo Mage::helper("adminhtml")->getUrl("connector/adminhtml_connector/mbizsettingwizard/");?>" method="post" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey')?>
        <div class="entry-edit-head collapseable">
            <a>Microbiz POS Plugin Install</a>
        </div>
        <fieldset id="connector_settings" class="config collapseable" style="background:none repeat scroll 0 0 #EEEEEE !important;">
            <legend>Microbiz POS Plugin Install</legend>
            <table cellspacing="0" class="form-list">
                <colgroup class="label"></colgroup>
                <colgroup class="value"></colgroup>
                <colgroup class="scope-label"></colgroup>
                <colgroup class=""></colgroup>
                <tbody>
                <tr>
                    <td colspan="3">
                        <div class="install_setup_img">
                            <img src="<?php echo $this->getSkinUrl('images/connector/step2.png')?>" alt="No Image" />
                        </div>
                    </td>
                </tr>
                <tr id="row_connector_install_mag_api_username">
                    <td class="label">
                        <img src="<?php echo $this->getSkinUrl('images/connector/microbiz.png')?>" width="59px" height="53px" />
                    </td>
                    <td style="vertical-align: middle;">
                        <div class="link_status" style="vertical-align: middle;font-size: 15px;"><?php echo "Linking ......"; ?></div>
                        <div class="link_success" style="vertical-align: middle;font-size: 15px;display:none;"><img src="<?php echo $this->getSkinUrl('images/connector/small-left.png')?>" width="15px"/><?php echo "Success!"; ?><img src="<?php echo $this->getSkinUrl('images/connector/small-right.png')?>" width="15px"/></div>
                        <div class="link_fail" style="vertical-align: middle;font-size: 15px;color:red;display:none;"><?php echo "! No Connection !"; ?></div>
                    </td>
                    <td class="value">
                        <img src="<?php echo $this->getSkinUrl('images/connector/magento.png')?>" width="40px" height="46px" />
                    </td>
                </tr>
                <tr><td colspan="3"></td></tr>
                <tr>
                    <td colspan="3">
                        <div class="link_status_message" style="font-size: 18px"></div>
                        <br />
                        <!--<div class="link_status_error" style="font-size: 18px">
        If your Magento site requires as SSL connection <a href="javascript:void(1)" class="get_ssl_conn">Please click here</a>
        </div>-->
                    </td>
                </tr>
                <?php
                $formKey = Mage::getSingleton('core/session')->getFormKey();
                ?>
                <tr>
                    <td colspan="2">
                        <?php $secretKey = Mage::getSingleton('adminhtml/url')->getSecretKey();?>
                        <button class="scalable back" id="back_to" type="button" title="Back" ><span><span><span>Back</span></span></span></button>
                        <!--<button class="scalable mbizform-cancelinstallpos" type="button" title="Cancel" ><span><span><span>Cancel</span></span></span></button>-->
                        <button class="scalable mbiz_install_save_api_link_form" type="button" disabled title="Save and Continue" ><span><span><span>Save and Continue</span></span></span></button>
                    </td>
                </tr>
                <?php
                $isSecure = Mage::app()->getStore()->isCurrentlySecure();
                $magentoBaseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, $isSecure);
                $mage_url = $magentoBaseUrl;
                //$mage_url_domain = explode('://',Mage::getBaseUrl());
                //print_r($mage_url_domain[1]);
                $formKey = $this->getBlockHtml('formkey');
                $mage_api_url = explode("/index.php/",$mage_url);
                Mage::helper('microbiz_connector')->RemoveCaching();
                Mage::helper('microbiz_connector')->RemoveCaching();
                $siteType = Mage::getStoreConfig('connector/installation/mbiz_sitetype');
                $sitename = Mage::getStoreConfig('connector/installation/mbiz_sitename');
                $siteurl = Mage::getStoreConfig('connector/installation/mbiz_siteurl');
                $username = Mage::getStoreConfig('connector/installation/mbiz_username');
                $password = Mage::getStoreConfig('connector/installation/mbiz_password');
                $magApiUname = Mage::getStoreConfig('connector/installation/mag_api_username');
                if($linkData['mag_api_email']) {

                }
                $magApiEmail = Mage::getStoreConfig('connector/installation/mag_api_email');
                $mbizApiUserName = Mage::getStoreConfig('connector/settings/api_user');
                $mbizApiUserPwd = Mage::getStoreConfig('connector/settings/api_key');
                $magApiUserPwd = Mage::getStoreConfig('connector/settings/mag_api_key');
                ?>

                <?php
                $sslData = array();
                $sslData['mbiz_site_name'] = $siteurl;
                $sslData['mag_site_name'] = $mage_api_url[0];;
                ?>
                <input type="hidden" id="is_linked_status" value="<?php echo $isLinked; ?>" />
                <input type="hidden" id="mage_url" name="mage_url" value="<?php echo $mage_api_url[0]; ?>">
                <input type="hidden" id="mbiz_back_url" name="mbiz_back_url" value="<?php echo Mage::helper("adminhtml")->getUrl("connector/adminhtml_connector/mbizvalidateinstallpos/"); ?>" />
                <input type="hidden" id="mbiz_sitetype" name="mbiz_sitetype" value="<?php echo $siteType ?>" />
                <input type="hidden" id="mbiz_sitename" name="mbiz_sitename" value="<?php echo $sitename; ?>" />
                <input type="hidden" id="mbiz_siteurl" name="mbiz_siteurl" value="<?php echo $siteurl; ?>" />
                <input type="hidden" id="mbiz_username" name="mbiz_username" value="<?php echo $username; ?>" />
                <input type="hidden" id="mbiz_password" name="mbiz_password" value="<?php echo $password; ?>" />
                <input type="hidden" id="mag_api_username" name="mag_api_username" value="<?php echo $magApiUname; ?>" />
                <input type="hidden" id="mag_api_email" name="mag_api_email" value="<?php echo $magApiEmail; ?>" />
                <input type="hidden" id="mag_api_password" name="mag_api_password" value="<?php echo $magApiUserPwd; ?>" />
                <input type="hidden" id="mbiz_api_username" name="mbiz_api_username" value="<?php echo $mbizApiUserName; ?>" />
                <input type="hidden" id="mbiz_api_password" name="mbiz_api_password" value="<?php echo $mbizApiUserPwd; ?>" />
                <input type="hidden" id="mbiz_posted_flag" name="mbiz_posted_flag" value="<?php echo $postedApiFlag ?>" />
                <input type="hidden" id="is_user_validated" name="is_user_validated" value="<?php echo $userNotExists; ?>" />
                </tbody>
            </table>
        </fieldset>
    </form>
</div>

<input type="hidden" id="link_data_url" value="<?php echo Mage::helper("adminhtml")->getUrl("connector/adminhtml_connector/mbizLinkApiUsers/"); ?>" />
<script type="text/javascript">
    jQuery(window).load(function(){
        var UserValidStatus = jQuery('#is_user_validated').val();
        console.log("uservalidatstatus = "+UserValidStatus);
//alert(UserValidStatus);return false;
        if(UserValidStatus==1) {
            checkLinkingStatus();
        }else {
            var LinkedStatus = jQuery('#is_linked_status').val();

            if(LinkedStatus==1) {
                jQuery(".link_status").hide();
                jQuery(".link_success").show();
                var mbizSiteType = jQuery('#mbiz_sitetype').val();
                if(mbizSiteType==1) {
                    var mbizSiteName = jQuery('#mbiz_sitename').val();
                    mbizSiteName = 'https://'+mbizSiteName+'.microbiz.com'
                }
                else {
                    var mbizSiteName = jQuery('#mbiz_sitename').val();
                }
                var magSiteName = jQuery('#mage_url').val();
                var status_msg = mbizSiteName+' is now linked to '+magSiteName;
                jQuery(".link_status_message").html(status_msg);
                jQuery(".mbiz_install_save_api_link_form").removeAttr("disabled");

            }
            else {
                jQuery(".link_status").hide();
                jQuery(".link_fail").show();
                var url = '<?php echo Mage::helper("adminhtml")->getUrl("connector/index/mbizGetSslConn/"); ?>';
                jQuery(".link_status_message").html("If your Magento site requires any SSL connection <a href='javascript:void(1)' action_url='"+url+"' class='get_ssl_conn'>Please click here</a>");
            }




        }
    });

    jQuery('#back_to').click(function(){
        //alert("came to f mbiz_back_url");
        var $mbizBackUrl = jQuery('#mbiz_back_url').val();
        jQuery("#mbiz_install_api_link_form").attr('action',$mbizBackUrl);
        jQuery("#mbiz_install_api_link_form").submit();
    });
    function checkLinkingStatus()
    {
        var linkData = {};
        linkData = <?php echo json_encode($linkData) ?>;
        var url = '<?php echo Mage::helper("adminhtml")->getUrl("connector/index/mbizLinkApiUsers/"); ?>';

        console.log("url = "+url);
        console.log(linkData);

        jQuery.ajax({
            url: url,
            dataType:'json',
            type: 'post',
            data: linkData,
            success: function(data){
                if(data.status=='SUCCESS') {
                    console.log("ajax request completed.");
                    console.log(data);
                    jQuery(".link_status").hide();
                    jQuery(".link_success").show();
                    jQuery(".link_status_message").html(data.status_msg);
                    jQuery("#mag_api_username").val(data.mag_api_username)
                    jQuery("#mag_api_password").val(data.mag_api_password)
                    jQuery("#mbiz_api_username").val(data.mbiz_api_username)
                    jQuery("#mbiz_api_password").val(data.mbiz_api_password)
                    jQuery(".success-msg").html("<ul><li><span>Magento Api User and Roles are Created in both Magento and Microbiz Instances. </span></li></ul>")
                    jQuery(".mbiz_install_save_api_link_form").removeAttr("disabled");

                }
                else {
                    jQuery(".link_status").hide();
                    jQuery(".link_fail").show();
                    var url = '<?php echo Mage::helper("adminhtml")->getUrl("connector/index/mbizGetSslConn/"); ?>';
                    jQuery(".success-msg").html("<ul><li><span>"+data.status_msg+" </span></li></ul>")
                    //alert(data.status_msg);
                    jQuery(".link_status_message").html("If your Magento site requires any SSL connection <a href='javascript:void(1)' action_url='"+url+"' class='get_ssl_conn'>Please click here</a>");
                    //                   alert(data.status_msg);
                    //shippingMethod.save();
                }
            }
        });

    }
    jQuery('.get_ssl_conn').live('click',function(){
        //alert("came to get ssl conn ");

        var magSiteName = jQuery('#mage_url').val();
        var mbizSiteName = jQuery('#mbiz_siteurl').val();
        console.log(magSiteName);
        console.log(mbizSiteName);

        if(magSiteName!='' && mbizSiteName!='') {
            jQuery('#loading-mask').show();
            url = jQuery('.get_ssl_conn').attr('action_url');
            var linkData = {};
            linkData = <?php echo json_encode($sslData) ?>;
            console.log(linkData);
            jQuery.ajax({
                url: url,
                dataType:'json',
                type: 'post',
                data: linkData,
                success: function(data){
                    if(data.status=='SUCCESS') {
                        jQuery('#loading-mask').hide();
                        alert(data.status_msg);

                    }
                    else {
                        jQuery('#loading-mask').hide();
                        alert(data.status_msg);
                    }
                },
                error: function(data)
                {
                    jQuery('#loading-mask').hide();
                }

            });
        }

    });
</script>
<script type="text/javascript">
    var mbizApiInfoForm = new varienForm('mbiz_install_api_link_form');
    jQuery('.mbiz_install_save_api_link_form').live('click',function(){
        var validated=mbizApiInfoForm.validate();
        if(validated){
            mbizApiInfoForm.submit();
        }
    });
</script>
