<?php // Version 100 ?>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)?>jquerylib/jquery-1.7.2.min.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)?>jquerylib/noconflict.js"></script>
<?php
$from = $this->getRequest()->getParam('fromId');
$to = $this->getRequest()->getParam('toId');
if(($from || $to) && $from <= $to) {
$customers = Mage::getModel('customer/customer')->getCollection()->addAttributeToSelect('*')->addAttributeToFilter('entity_id', array('gteq' => $from))->addAttributeToFilter('entity_id', array('lteq' => $to));
$msg = '';
    foreach($customers as $customer){
    try{
        $customer->setPosCusStatus(1);
        $customer->setSyncStatus(1);
        $customer->save();

        Mage::dispatchEvent('ktree_customer_save', array(
            'customer'  => $customer,
            'request'   => '',
            'olddata'   => '',
            'postdata'   => '',
        ));
    }
    catch(Exception $e){
        $msg .=  '<li><span>'.$customer->getId()."Not Saved due to Error". $e->getMessage()."</span></li>";
    }

}

    if(!$msg) { ?>
        <div id="messages"><ul class="messages"><li class="success-msg"><ul><li><span>All Customers Ids between (<?php echo $from." - ".$to;?>) Info saved into Sync Tables.</span></li></ul></li></ul></div>
    <?php
    }
    else {
        echo '<div id="messages"><ul class="messages"><li class="error-msg"><ul>'.$msg.'</ul></li></ul></div>';
    }
}
else if($from || $to){
    echo '<div id="messages"><ul class="messages"><li class="error-msg"><ul>Please Enter Valid From and To Values</ul></li></ul></div>';
}

    ?>

    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td><h3 class="icon-head"><?php echo Mage::helper('microbiz_connector')->__('Sync Customers') ?></h3>
                    <button style="float:right;" class="scalable mbizform" type="button" title="Save Config" id=""><span><span><span>Save Sync Information For Customers</span></span></span></button>	</td>
            </tr>
        </table>
    </div>
    <div class="entry-edit">

    <form id="mbiz_form" action="<?php echo $this->getUrl('*/*/customerSync') ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="customer_from_id">From Customer Id</label></td>
                <td class="value">
                    <input type="text" class="required-entry validate-digits validate-greater-than-zero input-text" value="" name="fromId" id="customer_from_id">
                </td>
            </tr>
            <tr>
                <td class="label"><label for="customer_to_id"> To Customer Id</label></td>
                <td class="value">
                    <input type="text" class="required-entry validate-digits validate-greater-than-zero input-text" value="" name="toId" id="customer_to_id">
                </td>
            </tr>
            </tbody>
        </table>

    </form>
    <script type="text/javascript">
        var importForm = new varienForm('mbiz_form');
        jQuery('.mbizform').live('click',function(){
            var validated=importForm.validate();
            if(validated){
                importForm.submit();
            }
        });
    </script>

    </div>
