<?php
$_agreements = $this->getAgreements();
if (!count($_agreements)) {
    return;
}
?>

<?php $outputType = Mage::getStoreConfig('firecheckout/agreements/output'); ?>
<ol class="checkout-agreements">
<?php $_i = 0; foreach ($_agreements as $_a): ?>
    <li<?php echo ++$_i === count($_agreements) ? ' class="last"' : ''?>>
        <div id="firecheckout-agreement-<?php echo $_a->getId() ?>-window"
            class="agreement-content"
            style="<?php echo 'minimal' === $outputType ? 'display: none;' : ($_a->getContentHeight() ? 'height:' . $_a->getContentHeight() : '') ?>"
        >
            <?php if ('minimal' === $outputType) : ?>
                <div class="page-title">
                    <span><?php echo $this->htmlEscape($_a->getName()) ?></span>
                </div>
            <?php endif; ?>
            <?php if ($_a->getIsHtml()):?>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
        </div>
        <p class="agree">
            <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" />
            <?php if ('minimal' === $outputType) : ?>
                <label for="agreement-<?php echo $_a->getId()?>">
                    <a href="javascript:void(0)" class="firecheckout-agreement-<?php echo $_a->getId() ?>">
                        <?php echo $this->htmlEscape($_a->getCheckboxText()) ?>
                    </a>
                </label>
            <?php else: ?>
                <label for="agreement-<?php echo $_a->getId()?>">
                    <?php echo $this->htmlEscape($_a->getCheckboxText()) ?>
                </label>
            <?php endif; ?>
        </p>
    </li>
<?php endforeach ?>
</ol>