<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): return; endif; ?>
<div id="firecheckout-forgot-window" style="display: none;">
    <div class="page-title">
        <span><?php echo $this->__('Forgot Your Password?') ?></span>
    </div>
    <form action="<?php echo $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'))) ?>" method="post" id="firecheckout-forgot-password-form">
        <div class="content">
            <?php
            $customerHelper = Mage::helper('customer');
            if (method_exists($customerHelper, 'generateResetPasswordLinkToken')) : ?>
                <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <?php else: ?>
                <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
            <?php endif; ?>
            <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="firecheckout-login"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('firecheckout-forgot-password-form', true);
    //]]>
    </script>
</div>
