<?php if ($this->getQuote()->isVirtual() || !Mage::getStoreConfig('firecheckout/general/shipping_address')) : return; endif; ?>
<ul class="form-list">
    <li class="control">
        <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Ship to the same address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Ship to the same address') ?></label>
    </li>
</ul>

<?php
    $_layout = $this->getLayout();
    $_isCustomerLoggedIn = $this->isCustomerLoggedIn();
    $_address = $this->getAddress();
    $_prefix  = 'shipping';

    $status = Mage::getStoreConfig('firecheckout/address_form_status');
    if ('hidden' !== $status['postcode']) {
        $status['postcode'] = 'required'; // used to render asterisk
    }
    if (Mage::getStoreConfig('general/region/state_required')) {
        $status['region'] = 'required'; // used to render asterisk
    }
    $fields = array(
        'name'  => array(),
        'company' => array(
            'class' => 'input-text',
            'label' => 'Company'
        ),
        'fax' => array(
            'class' => 'input-text',
            'label' => 'Fax'
        ),
        'telephone' => array(
            'class' => 'input-text',
            'label' => 'Telephone'
        ),
//        'city' => array(
//            'class' => 'input-text',
//            'label' => 'City'
//        ),
        'postcode' => array(
            'class' => 'input-text validate-zip-international',
            'label' => 'Zip/Postal Code'
        ),
//        'street1' => array(
//            'class' => 'input-text',
//            'label' => 'Address',
//            'title' => 'Street Address',
//            'name'  => $_prefix . '[street][]',
//            'value' => $_address->getStreet(1)
//        ),
        'country_id' => array(
            'label' => 'Country',
            'required_to_render' => 1
        ),
        'region' => array(
            'label' => 'State/Province',
            'required_to_render' => 1
        )
    );

    $addressHelper = $this->helper('customer/address');
    if (method_exists($addressHelper, 'isVatAttributeVisible')) {
        $fields['vat_id'] = array(
            'status' => $addressHelper->isVatAttributeVisible() ? 'optional' : 'hidden',
            'class'  => 'input-text ' . $addressHelper->getAttributeValidationClass('vat_id'),
            'label'  => 'VAT Number'
        );
    }
?>

<div id="shipping-address" class="firecheckout-section"<?php if($this->getAddress()->getSameAsBilling()): ?> style="display: none;"<?php endif; ?>>
    <div class="block-title"><span><?php echo $this->__('Shipping Address') ?></span></div>
    <div class="block-content">
        <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
           <li class="wide">
               <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
               <div class="input-box">
                   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
               </div>
           </li>
        <?php endif ?>
            <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                <fieldset>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                    <ul>
                        <?php foreach (Mage::helper('firecheckout/address')->getSortedFields() as $row) : ?>
                            <?php
                                $countVisible          = 0;
                                $countRequiredToRender = 0;

                                foreach ($row as $key => $field) { // do not use break in this cycle to fill statuses for all fields
                                    if (!isset($fields[$field])) { // shipping address doesn't have all of the fields
                                        unset($row[$key]);
                                        continue;
                                    }

                                    if (empty($status[$field])) {
                                        if (!empty($fields[$field]['status'])) {
                                            $status[$field] = $fields[$field]['status'];
                                        } else {
                                            $status[$field] = 'required';
                                        }
                                    }
                                    if (!empty($fields[$field]['required_to_render'])) {
                                        $countRequiredToRender++;
                                    }
                                    if ('hidden' !== $status[$field]) {
                                        $countVisible++;
                                    }
                                }

                                $isMulticolumn = ($countVisible > 1 || current($row) == 'name' || current($row) == 'postcode');
                            ?>

                            <?php if (!$countVisible && !$countRequiredToRender): continue; endif; ?>

                            <li class="<?php echo $isMulticolumn ? 'fields' : 'wide' ?>"<?php echo $countVisible ? '' : ' style="display: none;"' ?>>
                                <?php foreach ($row as $field) : ?>
                                    <?php $required = ('required' === $status[$field]); ?>

                                    <?php if ('name' === $field) : ?>
                                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($_address)->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('postcode' === $field) : ?>
                                        <div class="field">
                                            <label for="shipping:postcode" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('Zip/Postal Code') ?></label>
                                            <img id="postcode-shipping-please-wait" style="display:none;" src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('tig_postcode')->__('Loading...') ?>" title="<?php echo Mage::helper('tig_postcode')->__('Loading...') ?>" />
                                            <div class="input-box">
                                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry"/>
                                                <div style="display: none;" id="advice-validate:shipping:postcode" class="validation-advice"><?php echo Mage::helper('tig_postcode')->__('Check that the Zip/Postal Code and the House Number correctly entered!') ?></div>
                                            </div>
                                        </div>
                                        <div class="field  field-small">
                                            <label for="shipping:street2" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('House Number') ?></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('House Number') ?>" id="shipping:virtual:street2" value="" class="input-text required-entry"/>
                                            </div>
                                        </div>
                                        <div class="field  field-small">
                                            <label for="shipping:street3"><?php echo Mage::helper('tig_postcode')->__('Extension') ?></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Extension') ?>" id="shipping:virtual:street3" value="" class="input-text"/>
                                            </div>
                                        </div>
                                    <?php else : ?>

                                        <?php if ('hidden' === $status[$field]) :
                                            if (empty($fields[$field]['required_to_render'])) :
                                                continue;
                                            endif; ?>

                                            <div style="display: none;">
                                        <?php endif; ?>

                                        <?php if ($isMulticolumn) : ?>
                                            <div class="field">
                                        <?php endif; ?>

                                        <label for="<?php echo $_prefix ?>:<?php echo $field ?>"
                                            class="<?php echo $required ? 'required' : '' ?>"
                                            ><?php if ($required): ?><em>*</em><?php endif; ?><?php echo $this->__($fields[$field]['label']) ?></label>
                                        <div class="input-box">
                                            <?php if ('country_id' === $field) : ?>
                                                <?php echo $this->getCountryHtmlSelect($_prefix) ?>
                                            <?php elseif ('region' === $field): ?>
                                                <select id="<?php echo $_prefix ?>:region_id" name="<?php echo $_prefix ?>[region_id]"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="validate-select<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                                >
                                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                                </select>
                                                <script type="text/javascript">
                                                //<![CDATA[
                                                    $('<?php echo $_prefix ?>:region_id').setAttribute('defaultValue',  "<?php echo $_address->getRegionId() ?>");
                                                //]]>
                                                </script>
                                                <input type="text" id="<?php echo $_prefix ?>:region" name="<?php echo $_prefix ?>[region]"
                                                    value="<?php echo $this->htmlEscape($_address->getRegion()) ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="input-text<?php echo $required ? ' required-entry' : '' ?>" style="display:none;"
                                                />
                                            <?php else: ?>
                                                <?php
                                                    if (isset($fields[$field]['value'])):
                                                        $value = $fields[$field]['value'];
                                                    else:
                                                        $method = 'get' . ucfirst($field);
                                                        $value = $_address->{$method}();
                                                    endif;
                                                ?>
                                                <input type="text"
                                                    name="<?php echo (empty($fields[$field]['name']) ? $_prefix . '[' . $field . ']' : $fields[$field]['name']) ?>"
                                                    id="<?php echo $_prefix ?>:<?php echo $field ?>"
                                                    value="<?php echo $this->htmlEscape($value) ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="<?php echo $fields[$field]['class'] ?><?php echo $required ? ' required-entry' : '' ?>"
                                                />
                                            <?php endif ?>
                                        </div>

                                        <?php if ($isMulticolumn) : ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ('hidden' === $status[$field]) : ?>
                                            </div>
                                        <?php endif; ?>

                                    <?php endif; ?>

                                    <?php if ('postcode' === $field) : ?>
                                        </li>
                                        <?php if (Mage::getStoreConfig('tig_postcode/exclude_fields/field_extra_is_enabled')): ?>
                                            <li class="wide">
                                                <label class="required" for="shipping:street4"><?php echo Mage::helper('tig_postcode')->__('Extra') ?></label>
                                                <div class="input-box">
                                                    <input type="text" class="input-text" value="" id="shipping:virtual:street4" title="<?php echo Mage::helper('tig_postcode')->__('Extra') ?>" />
                                                </div>
                                            </li>
                                        <?php endif; ?>
                                        <li class="fields">
                                            <div class="field">
                                                <label for="shipping:street1" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('Street Address') ?></label>
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('Street Address') ?>" id="shipping:virtual:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry"/>
                                                </div>
                                            </div>
                                            <div class="field">
                                                <label for="shipping:city" class="required"><em>*</em><?php echo Mage::helper('tig_postcode')->__('City') ?></label>
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo Mage::helper('tig_postcode')->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="shipping:city"/>
                                                </div>
                                            </div>
                                    <?php endif; ?>

                                    <?php if ('street1' === $field) : ?>
                                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                            </li>
                                            <li class="wide">
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="<?php echo $_prefix ?>[street][]" id="<?php echo $_prefix ?>:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($_address->getStreet($_i)) ?>" class="input-text" />
                                                </div>
                                        <?php endfor ?>
                                    <?php endif; ?>

                                <?php endforeach; ?>
                            </li>
                        <?php endforeach; ?>

                    <?php $addressAttributes = $this->getChild('customer_form_' . $_prefix . '_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntity($_address)->setEntityType('customer_address');?>
                        <?php $addressAttributes->setFieldIdFormat($_prefix . ':%1$s')->setFieldNameFormat($_prefix . '[%1$s]');?>
                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>

                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                    </ul>
                </fieldset>
            </li>
        </ul>

        <?php for ($i=1;$i<5;$i++): ?>
        <input type="hidden" name="shipping[street][]" id="shipping:street<?php echo $i ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($i)) ?>" />
        <?php endfor;?>

        <script type="text/javascript">
        //<![CDATA[
            var shipping = new Shipping('firecheckout-form');
            var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');

            for (var i=1;i<5;i++) {
                var _virtualField = 'shipping:virtual:street'+i;
                var _field = 'shipping:street'+i;
                if ($(_virtualField)) $(_virtualField).value = $(_field).value;
            }
            tigPostcodeUpdaterShipping = new TigPostcodeUpdater('<?php echo $this->getUrl('tig_postcode/onepage', array('_secure' => true)); ?>', 'shipping:postcode', 'shipping:virtual:street2', 'shipping:virtual:street1', 'shipping:city', 'shipping:country_id', 'postcode-shipping-region', 'postcode-shipping-please-wait');
            document.observe('dom:loaded', function() {
                var btnCheckout = $('review-buttons-container').down('.btn-checkout');
                $('postcode-shipping-please-wait').observe('tigpostcodeupdater:start', function(e)    {
                    btnCheckout.setAttribute('disabled', 'disabled');
                });
                $('postcode-shipping-please-wait').observe('tigpostcodeupdater:stop', function(e)    {
                    btnCheckout.removeAttribute('disabled');
                });
                btnCheckout.observe('mousedown', function(e)    {
                    for (var i=1;i<5;i++) {
                        var _virtualField = 'shipping:virtual:street'+i;
                        var _field = 'shipping:street'+i;
                        if ($(_virtualField)) $(_field).value = $(_virtualField).value;
                    }
                });
                $('firecheckout-form').observe('submit', function(e)    {
                    for (var i=1;i<5;i++) {
                        var _virtualField = 'shipping:virtual:street'+i;
                        var _field = 'shipping:street'+i;
                        if ($(_virtualField)) $(_field).value = $(_virtualField).value;
                    }
                });
                if ($('shipping-address-select')) {
                    $('shipping-address-select').observe('change', function(e)    {
                        if ($('shipping-address-select').value == '') {
                            tigPostcodeUpdaterShipping.getData();
                        }
                    });
                }
                else {
                    tigPostcodeUpdaterShipping.getData();
                }
            });

        //]]>
        </script>
    </div>
</div>