<?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
    <nav class="navbar navbar-default mobile" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
			    <ul class="nav navbar-nav">
			        <?php echo $_menu ?>
			    </ul>
            </div>
    	</div>
    </nav>
<?php endif ?>