<?php
$quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();

if (!Mage::getStoreConfig('firecheckout/general/comment')) :
    return;
endif;

?>

<div class="clear"></div>
<div id="firecheckout_comment" class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="fieldset-legend head-firecheckout-comment-method icon-head"><?php echo $this->__('Customer Comment') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label for="firecheckout_customer_comment"><?php echo $this->__('Customer Comment') ?></label></td>
                        <td class="value">
                            <textarea class="input-text"
                                id="firecheckout_customer_comment"
                                name="firecheckout_customer_comment"
                                rows="2" cols="15"
                            ><?php echo $this->escapeHtml($quote->getFirecheckoutCustomerComment()); ?></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
